/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IQxE3p3irIv
 */
"use client ";
import {
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import DatabaseOperations from "@/lib/firebase/realtimedatabase/crud";
import { useState } from "react";
import { set } from "firebase/database";
export function Component() {
  let path = "Q&A";

  function createData(path: string, data: object) {
    const databaseOperations = new DatabaseOperations();
    databaseOperations
      .createData(path, data)
      .then(() => {
        console.log("Data created successfully");
        setQuestion("");
        setAnswer("");
      })
      .catch((error) => console.error("Failed to create data:", error));
  }
  const [answer, setAnswer] = useState("");
  const [question, setQuestion] = useState("");
  let data = {
    question: question,
    answer: answer,
  };
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <div className="space-y-2">
          <h2 className="text-3xl font-bold">Ask a question</h2>
          <p className="text-gray-500 dark:text-gray-400">
            HorizonのQ&Aを投稿してください
          </p>
        </div>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="space-y-2">
          <Label htmlFor="question">Question</Label>
          <Input
            id="question"
            placeholder="Enter your question"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="answer">Answer</Label>
          <Textarea
            className="min-h-[100px]"
            id="answer"
            placeholder="Enter your answer"
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
          />
        </div>
      </CardContent>
      <CardFooter>
        <Button
          onClick={() => {
            createData(path, data);
          }}
        >
          Submit
        </Button>
      </CardFooter>
    </Card>
  );
}
