/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IQxE3p3irIv
 */
import {
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import DatabaseOperations from "@/lib/firebase/realtimedatabase/crud";

export function Component() {
  function createData(path: string, data: object) {
    const databaseOperations = new DatabaseOperations();
    databaseOperations
      .createData(path, data)
      .then(() => console.log("Data created successfully"))
      .catch((error) => console.error("Failed to create data:", error));
  }
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <div className="space-y-2">
          <h2 className="text-3xl font-bold">Ask a question</h2>
          <p className="text-gray-500 dark:text-gray-400">
            HorizonのQ&Aを投稿してください
          </p>
        </div>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="space-y-2">
          <Label htmlFor="question">Question</Label>
          <Input id="question" placeholder="Enter your question" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="answer">Answer</Label>
          <Textarea
            className="min-h-[100px]"
            id="answer"
            placeholder="Enter your answer"
          />
        </div>
      </CardContent>
      <CardFooter>
        <Button onClick={() => createData}>Submit</Button>
      </CardFooter>
    </Card>
  );
}
